# Generated by Django 5.2.6 on 2025-09-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='data/documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(upload_to='data/images/'),
        ),
    ]
