# Generated by Django 5.2.6 on 2025-09-06 05:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_document_author_alter_document_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
