# Generated by Django 5.2.6 on 2025-09-08 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_author_alter_document_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='app.author'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(default='data/documents/Bai_tap_nhom_2025.pdf', upload_to='data/documents'),
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(default='data/images/codeimage-snippet_7.png', upload_to='data/images'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
