# Generated by Django 5.2.6 on 2025-09-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_uploaded_at_document_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='data/documents'),
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='data/images'),
        ),
    ]
